//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DSIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3DSIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;string.h&gt;
        ///#include &lt;stdio.h&gt;
        ///
        ///#include &lt;3ds.h&gt;
        ///
        ///int main(int argc, char **argv) {
        ///
        ///	gfxInitDefault();
        ///	consoleInit(GFX_TOP, NULL);
        ///
        ///	printf(&quot;Hello 3DS World!&quot;);
        ///
        ///
        ///	// Main loop
        ///	while (aptMainLoop()) {
        ///
        ///		gspWaitForVBlank();
        ///		hidScanInput();
        ///
        ///		// Your code goes here
        ///
        ///		u32 kDown = hidKeysDown();
        ///		if (kDown &amp; KEY_START)
        ///			break; // break in order to return to hbmenu
        ///
        ///		// Flush and swap framebuffers
        ///		gfxFlushBuffers();
        ///		gfxSwapBuffers();
        ///	}
        ///
        ///	gfxExit();
        ///	return  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #---------------------------------------------------------------------------------
        ///.SUFFIXES:
        ///#---------------------------------------------------------------------------------
        ///
        ///ifeq ($(strip $(DEVKITARM)),)
        ///$(error &quot;Please set DEVKITARM in your environment. export DEVKITARM=&lt;path to&gt;devkitARM&quot;)
        ///endif
        ///
        ///TOPDIR ?= $(CURDIR)
        ///include $(DEVKITARM)/3ds_rules
        ///
        ///#---------------------------------------------------------------------------------
        ///# TARGET is the name of the output
        ///# BUILD is the directory  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Makefile {
            get {
                return ResourceManager.GetString("Makefile", resourceCulture);
            }
        }
    }
}
